name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
      #Checkout the repo
      - uses: actions/checkout@v3

      #Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      #Install dependencies
      - name: Install all dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      #processing scripts py and cpp
      - name: Run processing scripts
        run: |
          python scripts/process_events.py -i .github/data/dummy.parquet -o output_py.parquet -m py
          python scripts/process_events.py -i .github/data/dummy.parquet -o output_cpp.parquet -m cpp

      #Compare py and cpp outputs
      - name: Compare outputs
        run: |
          python -c 'from common.parquetComparison import areFilesIdentical; areFilesIdentical("output_py.parquet","output_cpp.parquet",throwError=True)'
